### ISSUE TITLE
Migrate from classic to V2

### ISSUE THREAD

**Issue by omar-dulaimi** [awslabs/aws-waf-security-automations#138]
Hello,
What is the proper way to migrate our current AWS WAF classic to the latest AWS WAFv2 using this same template, since we used it in the past.

We don't want to break any lambda handlers, etc.

Is there a guide we can follow, since I read somewhere that we should wait until the template is updated.

**Comment by aijunpeng** [comment]
You can't use the same template to update the solution from WAF classic to WAFv2.  You will need to deploy the WAF 3.0 solution as a new solution to switch to WAFv2. The new solution will deploy the resources in WAFv2.

**Comment by omar-dulaimi** [comment]
@aijunpeng What about the IPSets that I've created?
will I be able to reuse them?

Also, the v2 template, is it customizeable through the console?
And I read that supports more logical operations in conditions besides the old AND in v1?

**Comment by aijunpeng** [comment]
If you create your own IPSets in AWS WAF classic you will need to create them again in WAFv2 because WAF classic and WAFv2 services are not compatible with each other and they don't share IPSets. Can you clarify what you mean by "the v2 template, is it customizeable through the console?" ? If you are asking that if rules are customizable at solution deployment, the answer is no. You can customize rules through the WAF service console after deploying the solution

**Comment by omar-dulaimi** [comment]
Yeah that's what I meant. Thank you for explaining.

**Comment by ismunday** [comment]
Are there plans to migrate the AWS WAF Security Automations project to WAFv2 rather than WAF Classic?
