### ISSUE TITLE
Error on merging current blocked requesters

### ISSUE THREAD

**Issue by dix-icomys** [awslabs/aws-waf-security-automations#18]
Hello, using WAF Regional stack for a few days, and found this on LambdaWAFLogParserFunction log:

```
[merge_current_blocked_requesters]   Calculate Last Update Age
[merge_current_blocked_requesters]   Download current blocked IPs
[merge_current_blocked_requesters]   Expire Block IP rules
[merge_current_blocked_requesters]   Error merging 140.119.169.126 rule
can't subtract offset-naive and offset-aware datetimes
[merge_current_blocked_requesters] End
```

**Comment by jpbelangerupgrade** [comment]
the problem comes from the `total_diff_min = ((now_timestamp - prev_updated_at).total_seconds())/60` lines. the prev_update_at does not have any timezone associated to it. I had to add the UTC timezone to it for it to work.

**Comment by dix-icomys** [comment]
Thanks, @jpbelangerupgrade

**Comment by michi88** [comment]
it can be fixed with:
```python
from dateutil import tz

# somewhere around line 185
# fix for https://github.com/awslabs/aws-waf-security-automations/issues/18
prev_updated_at = prev_updated_at.replace(tzinfo=tz.tzutc())
# end fix
```

**Comment by nokiomanz** [comment]
Hi all,

I was using the solution from before the last "stack" update on the 29 jully 2017. And it was working great.
When the updated stack got updated I updated it. I realised this morning that it was not working properly with the same reason provided by @thechrisproject here : https://github.com/awslabs/aws-waf-security-automations/issues/25. Not that big of a deal because those ip making too much request get's blocked again. It was just not working as expected by following the amount of time I wanted to block.

I added after line 184
prev_updated_at = prev_updated_at.replace(tzinfo=response['LastModified'].tzinfo)

Before :
prev_updated_at = datetime.datetime.strptime(v['updated_at'], "%Y-%m-%d %H:%M:%S")
total_diff_min = ((now_timestamp - prev_updated_at).total_seconds())/60

After :
prev_updated_at = datetime.datetime.strptime(v['updated_at'], "%Y-%m-%d %H:%M:%S")
prev_updated_at = prev_updated_at.replace(tzinfo=response['LastModified'].tzinfo)
total_diff_min = ((now_timestamp - prev_updated_at).total_seconds())/60

It now work as expected.

**Comment by hvital** [comment]
Hi, 

Thanks for the comment and recommendation about how to fix it.

The current version is supposed to use the same timezone. [Here](https://github.com/awslabs/aws-waf-security-automations/blob/c7b25b4f9005469f1606e8da19c9704268f0697a/source/log-parser/log-parser.py#L190).
