### ISSUE TITLE
TypeError: can't subtract offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by thechrisproject** [awslabs/aws-waf-security-automations#25]
https://github.com/awslabs/aws-waf-security-automations/blob/beca5eb31b55dcba291b5ad1a91a0ba687292402/source/log-parser/log-parser.py#L185

This code for me resulted in the error in the subject. I'm not much of a python person but I reproduced the problem locally and fixed it by assigning prev_update_at a value with the same tzinfo as the response['LastModified'], which comes from the head_object request for the aws-waf-security-automations-current-blocked-ips.json file. 

Here was my fix, inserted after line 185:

`prev_updated_at = prev_updated_at.replace(tzinfo=response['LastModified'].tzinfo)`

The result of the error was the the merge list was computed improperly and I only ever had one blocked IP in my WAF rule.

**Comment by orfin** [comment]
We're also running int the same problem.
@hvital I saw that you are active in this project - can you please let us know if AWS team plans to fix that, or we should just submit PR?

**Comment by nokiomanz** [comment]
Hi all, 

I was using the solution from before the last "stack" update on the 29 jully 2017. And it was working great. 
When the updated stack got updated I updated it. I realised this morning that it was not working properly with the same reason provided by @thechrisproject. Not that big of a deal because those ip making too much request get's blocked again. It was just not working as expected by following the amount of time I wanted to block.

I added after line 184
prev_updated_at = prev_updated_at.replace(tzinfo=response['LastModified'].tzinfo)

Before : 
prev_updated_at = datetime.datetime.strptime(v['updated_at'], "%Y-%m-%d %H:%M:%S")
total_diff_min = ((now_timestamp - prev_updated_at).total_seconds())/60

After : 
prev_updated_at = datetime.datetime.strptime(v['updated_at'], "%Y-%m-%d %H:%M:%S")
prev_updated_at = prev_updated_at.replace(tzinfo=response['LastModified'].tzinfo)
total_diff_min = ((now_timestamp - prev_updated_at).total_seconds())/60

It now work as expected.

**Comment by hvital** [comment]
Thanks for the feedback. We're working on a new version and will incorporate this fix!

**Comment by nokiomanz** [comment]
Hi, 

Can be closed with the release of version 2.1
