### ISSUE TITLE
XSS Rule blocks upload images on wordpress

### ISSUE THREAD

**Issue by daniele2112** [awslabs/aws-waf-security-automations#52]
The xss rules blocks the uploads of some images from the WP backoffice.

I deleted the rule "Body contains a cross-site scripting threat after decoding as URL" and it stopped to block the uploads".

**Comment by eric5102** [comment]
WP has known cross site scripting vulnerabilities: 
https://www.exploit-db.com/exploits/44443/
https://www.exploit-db.com/exploits/44444/
etc.
if it is a different bug you may also want to fix the WP bug and share the fix with the WP community

Instead of removing protection you may want to:
1. make sure WP has the latest security patches
2. Add your office IP to the whitelist rule. If the request is allowed by a preceding rule the XSS rule won't be evaluated. This assumes you are not allowing public uploads
