### ISSUE TITLE
Need control over WAF name - do not want randomized

### ISSUE THREAD

**Issue by torinwalker** [awslabs/aws-waf-security-automations#77]
We have deployed 2.1 previously. In the new 2.2 release, the stack deployment shows two stack deployments, one of which is named as I typed it, and the other (which is how the WAF name ends up) has some hyphenated, randomized suffix added to it.

Naming conventions in AWS are already difficult enough to manage in a large organization - not being able to name the WAF exactly how we need is maddening.

Please provide either a suggestion on what code to tweak to prevent this random suffix from being added, or provide an option to control it during deployment. The current version with its forced-naming convention is unacceptable.

**Comment by hvital** [comment]
Hi @torinwalker 

Thanks for your feedback!

We're going to change the name conversion in next version. Some resources will use the main stack's name (not the nested stack's name - that contains those random characters you've mentioned) as prefix. 

The idea is to instead of using the following name structure:
`Name: !Join [' - ', [!Ref 'AWS::StackName', 'Whitelist Set']]`
	
Use this:
`Name: !Sub '${ParentStackName} - Whitelist Set'`

Direct link for this example in **ALB** template [here](https://github.com/awslabs/aws-waf-security-automations/blob/c7b25b4f9005469f1606e8da19c9704268f0697a/deployment/aws-waf-security-automations-alb.template#L76) and **CloufFront** [here](https://github.com/awslabs/aws-waf-security-automations/blob/c7b25b4f9005469f1606e8da19c9704268f0697a/deployment/aws-waf-security-automations-cloudfront.template#L76). 

Does it help you?

Regards,

**Comment by trav-c** [comment]
If I'm reading the change linked in the previous post correctly the resource names will still be dictated by the name of all parent stacks back to the root above the main WAF automation stack.

I'd personally really like to be able to pass a base-name in as a parameter, particularly since in my current use-case I'm pulling the WAF stack in from an already nested stack meaning names based on the stack name still contain random strings.

**Comment by hvital** [comment]
Got your point @trav-c 

Unfortunately, we wont have time to include this change in v2.3.0 as we're running the final tests/reviews in order to publish it. 

As soon as we have the new version published, I'll come back here and give you guidance about how to change the template to add this extra input parameter (so you can set custom prefix name for resources' names). 

Regards, 

Heitor

**Comment by hvital** [comment]
Hi @trav-c 

I pushed v2.3.0. As I mentioned, we are using the Parent's stack name to prefix AWS WAF resources' name. 

For you case, you can change [this (for ALB/Regional WAF)](https://github.com/awslabs/aws-waf-security-automations/blob/e504013c87bde6d6af434097f0c1147a4c1f86c0/deployment/aws-waf-security-automations.template#L414) and [this (for CloudFront/Global WAF)](https://github.com/awslabs/aws-waf-security-automations/blob/e504013c87bde6d6af434097f0c1147a4c1f86c0/deployment/aws-waf-security-automations.template#L440) resource. 

If it makes sense, you can add this as [input parameter](https://github.com/awslabs/aws-waf-security-automations/blob/e504013c87bde6d6af434097f0c1147a4c1f86c0/deployment/aws-waf-security-automations.template#L180) or [mapping](https://github.com/awslabs/aws-waf-security-automations/blob/e504013c87bde6d6af434097f0c1147a4c1f86c0/deployment/aws-waf-security-automations.template#L265) in the main template.
